In [ ]:


pip install opencv-python


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2

dir = "/Users/flo/Desktop/456/project/food-101/images"
classes = ["bibimbap","falafel"]

print (classes)

for cl in classes:
    path = os.path.join(dir, cl)
    for img in os.listdir(path):
        img_arr = cv2.imread(os.path.join(path,img)) 
        plt.imshow(img_arr)
        plt.show()
        break
    break

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2

dir = "/Users/flo/Desktop/456/project/food-101/images_test"
classes = ["bibimbap","donuts"]

for cl in classes:
    path = os.path.join(dir, cl) # path = /Users/flo/Desktop/456/project/food-101/images/bibimbap
    #print(path)
    label = classes.index(cl)
    print(classes.index(cl))
    input('wait')
    for img in os.listdir(path): # img = 3845303.jpg
        if img.startswith('.'): # .DS_Store
            break
        try: 
            img_bgr = cv2.imread(os.path.join(path,img)) # imread takes in path to foodpic.jpg
            img_rgb = img_bgr[:, :, ::-1] # imread defaults to BGR, so convert into RGB
            plt.imshow(img_rgb)
            plt.show() 
            #training_data.append([img_rgb, label])
        except Exception as e:
            pass
        #print(img_rgb.shape) # (512, 384, 3) => 3845303.jpg is 384 x 512 dimensions
        #input('wait')
        


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2

for cl in classes:
    path = os.path.join(dir, cl) # path = /Users/flo/Desktop/456/project/food-101/images/bibimbap
    label = classes.index(cl)
    for img in os.listdir(path): # img = 3845303.jpg
        if img.startswith('.'): # .DS_Store
            break
        try: 
            img_bgr = cv2.imread(os.path.join(path,img)) # imread takes in path to foodpic.jpg
            img_rgb = img_bgr[:, :, ::-1] # imread defaults to BGR, so convert into RGB
            #plt.imshow(img_rgb)
            #plt.show() 
            print('appending',img_rgb)
            training_data.append([img_rgb, label])
        except Exception as e:
            pass
        break
    break
        #print(img_rgb.shape) # (512, 384, 3) => 3845303.jpg is 384 x 512 dimensions
        #input('wait')
    

In [6]:
dir = "/Users/flo/Desktop/456/project/food-101/images_test/bibimbap/3924141.jpg"

img = cv2.imread(dir)

print(img.shape)
print(img)



(512, 512, 3)
[[[ 87 101 120]
  [ 96 107 127]
  [112 121 141]
  ...
  [ 57 129 189]
  [ 59 126 187]
  [ 57 124 185]]

 [[ 93 104 126]
  [ 96 107 129]
  [108 114 137]
  ...
  [ 57 127 187]
  [ 52 119 182]
  [ 53 118 179]]

 [[105 112 137]
  [108 113 138]
  [115 116 142]
  ...
  [ 51 118 181]
  [ 46 107 173]
  [ 45 107 171]]

 ...

 [[ 51  76 148]
  [ 48  74 141]
  [ 32  56 114]
  ...
  [ 15  36  98]
  [ 15  34  95]
  [ 19  38  99]]

 [[ 50  74 158]
  [ 41  64 144]
  [ 33  55 126]
  ...
  [  2  19  75]
  [ 10  26  79]
  [ 24  38  90]]

 [[ 49  73 163]
  [ 28  52 136]
  [ 28  48 125]
  ...
  [  0  12  61]
  [ 11  25  74]
  [ 32  44  92]]]


In [4]:
IMG_SIZE = 100

# new_img = cv2.resize(img_rgb, (IMG_SIZE,IMG_SIZE))
# plt.imshow(new_img)
# plt.show()  
# print(new_img.shape)


In [9]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2

training_data = []

def create_training_data(dir, classes):
    for cl in classes:
        path = os.path.join(dir, cl) # path = /Users/flo/Desktop/456/project/food-101/images/bibimbap
        label = classes.index(cl)
        for img in os.listdir(path): # img = 3845303.jpg
            #print('image',img)
            if img.startswith('.'): # .DS_Store
                continue
            #print(img,'good to go')
            try: 
                img_bgr = cv2.imread(os.path.join(path,img)) # imread takes in path to foodpic.jpg
                img_rgb = img_bgr[:, :, ::-1] # imread defaults to BGR, so convert into RGB
                new_img = cv2.resize(img_rgb, (IMG_SIZE,IMG_SIZE))
                
                #print('shape',new_img.shape)
                training_data.append([new_img, label]) # td is array of <100x100x3 img, label>
            except Exception as e:
                print("exception thrown: ",e)
            #input('wait')
    return training_data

dir = "/Users/flo/Desktop/456/project/food-101/images_test"
classes = ["bibimbap","donuts"]

td = create_training_data(dir, classes)
print(td)

[[array([[[143, 117, 116],
        [144, 110, 104],
        [187, 138, 116],
        ...,
        [160,  98,  46],
        [171, 106,  51],
        [181, 118,  51]],

       [[189, 142, 131],
        [177, 131, 117],
        [194, 143, 109],
        ...,
        [131,  69,  33],
        [165,  99,  50],
        [150,  79,  38]],

       [[189, 138, 114],
        [160, 109,  87],
        [218, 160, 129],
        ...,
        [131,  77,  39],
        [102,  46,  21],
        [ 82,  29,   4]],

       ...,

       [[110,  53,  20],
        [ 42,   8,   3],
        [103,  62,  34],
        ...,
        [148,  86,  41],
        [ 83,  38,  12],
        [ 47,  15,   7]],

       [[ 68,  30,   7],
        [ 50,  29,  24],
        [ 53,  22,  11],
        ...,
        [101,  40,  10],
        [106,  43,  15],
        [ 86,  30,  10]],

       [[111,  53,  29],
        [ 67,  24,   8],
        [103,  55,  27],
        ...,
        [ 96,  43,  13],
        [103,  38,   8],
        [ 99,  37,  15

In [12]:
import random
random.shuffle(td)

In [16]:
for s in td:
    print(s[1])

0
1


In [27]:
X = []
y = []

for features, label in td:
    X.append(features)
    y.append(label)
    
#print('X',X)
#print('y',y)

X = np.array(X).reshape(-1, IMG_SIZE, IMG_SIZE, 3) # -1 = any number of features
print(X)

[[[[143 117 116]
   [144 110 104]
   [187 138 116]
   ...
   [160  98  46]
   [171 106  51]
   [181 118  51]]

  [[189 142 131]
   [177 131 117]
   [194 143 109]
   ...
   [131  69  33]
   [165  99  50]
   [150  79  38]]

  [[189 138 114]
   [160 109  87]
   [218 160 129]
   ...
   [131  77  39]
   [102  46  21]
   [ 82  29   4]]

  ...

  [[110  53  20]
   [ 42   8   3]
   [103  62  34]
   ...
   [148  86  41]
   [ 83  38  12]
   [ 47  15   7]]

  [[ 68  30   7]
   [ 50  29  24]
   [ 53  22  11]
   ...
   [101  40  10]
   [106  43  15]
   [ 86  30  10]]

  [[111  53  29]
   [ 67  24   8]
   [103  55  27]
   ...
   [ 96  43  13]
   [103  38   8]
   [ 99  37  15]]]


 [[[  4   4   4]
   [  4   4   4]
   [  3   3   3]
   ...
   [  4   4   4]
   [  5   5   5]
   [  5   5   5]]

  [[  6   6   6]
   [  3   3   3]
   [  2   2   2]
   ...
   [  4   4   4]
   [  4   4   4]
   [  4   4   4]]

  [[  4   4   4]
   [  4   4   4]
   [  2   2   2]
   ...
   [  5   5   5]
   [  6   6   6]
   [  4   4